[livelystage_lives_upcoming]
title = "Lively ─ 다가오는 공연"
url = "https://livelystage.com/lives/upcoming"
entrySelector = "div._relative_dg4qx_1._flex_8t66z_13 a"
titleSelector = "div > div._relative_dg4qx_1._app_p_mont_a6o19_1._wrap_a6o19_377._keepWord_a6o19_382._secondary_a6o19_1._none_1f8id_1"
linkSelector = "*"
contentSelector = "div > div:nth-child(4) > div._relative_dg4qx_1._app_small_a6o19_1._wrap_a6o19_377._keepWord_a6o19_382._none_1f8id_1"
imageSelector = "div > div:nth-child(1) > div > div > picture > img"
waitUntil = "networkidle"

[livelystage_lives_upcoming_legacy]
title = "Lively ─ 다가오는 공연"
url = "https://livelystage.com/lives/upcoming"
entrySelector = "div._relative_dg4qx_1._flex_8t66z_13 a"
titleSelector = "div > div:nth-child(4) > div._relative_dg4qx_1._app_p_a6o19_1._wrap_a6o19_377._keepWord_a6o19_382._none_1f8id_1"
linkSelector = "*"
contentSelector = "div > div:nth-child(4) > div._relative_dg4qx_1._app_small_a6o19_1._wrap_a6o19_377._keepWord_a6o19_382._none_1f8id_1"
imageSelector = "div > div:nth-child(1) > div > div > picture > img"
waitUntil = "networkidle"

[livelystage_lives_finished]
title = "Lively ─ 지난 공연"
url = "https://livelystage.com/lives/finished"
entrySelector = "div._relative_dg4qx_1._flex_8t66z_13 a"
titleSelector = "div > div._relative_dg4qx_1._app_p_mont_a6o19_1._wrap_a6o19_377._keepWord_a6o19_382._secondary_a6o19_1._none_1f8id_1"
linkSelector = "*"
contentSelector = "div > div:nth-child(4) > div._relative_dg4qx_1._app_small_a6o19_1._wrap_a6o19_377._keepWord_a6o19_382._none_1f8id_1"
imageSelector = "div > div:nth-child(1) > div > div > picture > img"
waitUntil = "networkidle"

[livelystage_lives_finished_legacy]
title = "Lively ─ 지난 공연"
url = "https://livelystage.com/lives/finished"
entrySelector = "div._relative_dg4qx_1._flex_8t66z_13 a"
titleSelector = "div > div:nth-child(4) > div._relative_dg4qx_1._app_p_a6o19_1._wrap_a6o19_377._keepWord_a6o19_382._none_1f8id_1"
linkSelector = "*"
contentSelector = "div > div:nth-child(4) > div._relative_dg4qx_1._app_small_a6o19_1._wrap_a6o19_377._keepWord_a6o19_382._none_1f8id_1"
imageSelector = "div > div:nth-child(1) > div > div > picture > img"
waitUntil = "networkidle"
